### ISSUE TITLE
error cython

### ISSUE THREAD

**Issue by huytq97** [Sanster/tf_ctpn#4]
Thanks for your code and dataset!
I have one error when from lib.utils.cython_bbox import bbox_overlaps
/usr/bin/python3.5 /home/tangquanghuy/Documents/sourcecode/tf_ctpn-master/tools/trainval_net.py
Traceback (most recent call last):
  File "/home/tangquanghuy/Documents/sourcecode/tf_ctpn-master/tools/trainval_net.py", line 13, in <module>
    from lib.datasets.factory import get_imdb
  File "/home/tangquanghuy/Documents/sourcecode/tf_ctpn-master/lib/datasets/factory.py", line 14, in <module>
    from datasets.pascal_voc import pascal_voc
  File "/home/tangquanghuy/Documents/sourcecode/tf_ctpn-master/tools/../lib/datasets/pascal_voc.py", line 12, in <module>
    from lib.datasets.imdb import imdb
  File "/home/tangquanghuy/Documents/sourcecode/tf_ctpn-master/lib/datasets/imdb.py", line 14, in <module>
    from lib.utils.cython_bbox import bbox_overlaps
ImportError: No module named 'lib.utils.cython_bbox'

**Comment by zjchuyp** [comment]
Compile bbox first.

**Comment by Sanster** [comment]
@huytq97 Have you compile Cython code?

```bash
cd lib/
make clean
make
```
